version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - .:/workspace
    privileged: true

  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform_service
    volumes:
      - ./terraform:/app
    working_dir: /app
    entrypoint: ["terraform"]

  ansible:
    image: ubuntu:22.04
    container_name: ansible_service
    volumes:
      - ./ansible:/ansible
    working_dir: /ansible
    command: tail -f /dev/null

